config/routes.rb
Rails.application.routes.draw do
  scope :module => 'gluttonberg' do
    namespace :admin do
      scope :module => 'blog' do
        scope 'comments', :controller => :comments, :as => :comments do
          get 'spam_detection_for_all_pending' , :as => :spam_detection_for_all_pending
          get 'pending', :as => :pending
          get 'spam' , :as => :spam
          get 'approved' , :as => :approved
          get 'rejected' => :rejected , :as => :rejected
          get '/moderation/:id/:moderation' => :moderation , :as => :moderation
          get '/delete/:id' => :delete , :as => :delete
          delete '/destroy/:id' => :destroy , :as => :destroy
          get '/block_author/:id' => :block_author , :as => :block_author
        end

        resources :blogs do
          get 'delete', :on => :member
          resources :articles do
            member do
              get 'delete'
              get 'duplicate'
            end
            collection do
              match 'import'
              get 'export'
            end
            resources :comments do
              member do
                get 'delete'
              end
            end
          end
        end # blogs
      end #blog module
    end #admin
    scope :module => 'public' do
      # Blog Stuff
      scope :module => 'blog' do
        get "/articles/tag/:tag" => "articles#tag" , :as => :articles_by_tag
        get "/articles/unsubscribe/:reference" => "articles#unsubscribe" , :as => :unsubscribe_article_comments
        scope "(/:locale)" do
          resources :blogs do
            resources :articles do
              resources :comments
              get "preview"
            end
          end
        end
      end
    end#public
  end #gluttonberg
end

app/models/gluttonberg/blog/comment_subscription.rb
module Gluttonberg
  module Blog
    class CommentSubscription < ActiveRecord::Base
      self.table_name = "gb_comment_subscriptions"

      before_save    :generate_reference_hash
      belongs_to     :article

      attr_accessible :article_id , :author_email , :author_name
      MixinManager.load_mixins(self)

      def self.notify_subscribers_of(article , comment)
        subscribers = self.where(:article_id => article.id).all
        subscribers.each do |subscriber|
          unless subscriber.author_email == comment.writer_email
            BlogNotifier.delay.comment_notification(subscriber , article , comment )
            comment.notification_sent_at = Time.now
            comment.save
          end
        end
      end

      def generate_reference_hash
        unless self.reference_hash
          self.reference_hash = Digest::SHA1.hexdigest(Time.now.to_s + self.author_email + self.article_id.to_s)
        end
      end

    end
  end
end

app/models/gluttonberg/blog/weblog.rb
module Gluttonberg
  module Blog
    class Weblog < ActiveRecord::Base
      self.table_name = "gb_weblogs"
      include Content::Publishable
      include Content::SlugManagement
      MixinManager.load_mixins(self)
      
      belongs_to :user
      has_many :articles, :dependent => :destroy, :foreign_key => 'blog_id'
      belongs_to :fb_icon , :class_name => "Gluttonberg::Asset" , :foreign_key => "fb_icon_id"

      validates_presence_of :name, :user_id

      is_versioned :non_versioned_columns => ['state' ,'published_at' , 'moderation_required' ]

      acts_as_taggable_on :tag
      clean_html [:description]
      attr_accessible :user_id, :name, :slug, :description, :moderation_required
      attr_accessible :user
      attr_accessible :seo_title, :seo_keywords, :seo_description, :fb_icon_id, :state, :published_at

    end
  end
end

app/controllers/gluttonberg/admin/blog/application_controller.rb
module Gluttonberg
  module Blog
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/gluttonberg/admin/blog/articles_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module Blog
      class ArticlesController < Gluttonberg::Admin::BaseController
        before_filter :find_blog , :except => [:create]
        before_filter :find_article, :only => [:show, :edit, :update, :delete, :destroy , :duplicate]
        before_filter :authorize_user , :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]
        record_history :@article , :title
        before_filter :all_articles, :only => [:index, :export]

        def index
          @articles = @articles.paginate({
            :per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"),
            :page => params[:page]
          })
        end

        def show
          @comment = Gluttonberg::Blog::Comment.new
        end

        def new
          @article = Gluttonberg::Blog::Article.new
          @article_localization = Gluttonberg::Blog::ArticleLocalization.new(:article => @article , :locale_id => Locale.first_default.id)
          @authors = User.all
        end

        def create
          params[:gluttonberg_blog_article_localization][:article][:name] = params[:gluttonberg_blog_article_localization][:title]
          article_attributes = params["gluttonberg_blog_article_localization"].delete(:article)
          @article = Gluttonberg::Blog::Article.new(article_attributes)
          if @article.save
            @article.create_localizations(params["gluttonberg_blog_article_localization"])
            flash[:notice] = "The article was successfully created."
            redirect_to edit_admin_blog_article_path(@article.blog, @article)
          else
            render :edit
          end
        end

        def edit
          @authors = User.all
          unless params[:version].blank?
            @version = params[:version]
            @article_localization.revert_to(@version)
          end
        end

        def update
          article_attributes = params["gluttonberg_blog_article_localization"].delete(:article)
          @article_localization.article.assign_attributes(article_attributes)
          @article_localization.current_user_id = current_user.id
          @article_localization.updated_at = Time.now

          if @article_localization.update_attributes(params[:gluttonberg_blog_article_localization])            
            @article_localization.article.save
            _log_article_changes

            flash[:notice] = "The article was successfully updated."
            redirect_to edit_admin_blog_article_path(@article.blog, @article) + (@article_localization.reload && @article_localization.versions.latest.version != @article_localization.version ? "?version=#{@article_localization.versions.latest.version}" : "")
          else
            flash[:error] = "Sorry, The article could not be updated."
            render :edit
          end
        end

        def delete
          display_delete_confirmation(
            :title      => "Delete Article '#{@article.title}'?",
            :url        => admin_blog_article_path(@blog, @article),
            :return_url => admin_blog_articles_path(@blog),
            :warning    => ""
          )
        end

        def destroy
          @article.current_localization
          generic_destroy(@article, {
            :name => "article",
            :success_path => admin_blog_articles_path(@blog),
            :failure_path => admin_blog_articles_path(@blog)
          })
        end

        def duplicate
          @duplicated_article = @article.duplicate
          @duplicated_article.user_id = current_user.id
          if @duplicated_article
            flash[:notice] = "The article was successfully duplicated."
            redirect_to edit_admin_blog_article_path(@blog, @duplicated_article)
          else
            flash[:error] = "There was an error duplicating the article."
            redirect_to admin_blog_articles_path(@blog)
          end
        end

        def import
          unless params[:csv].blank?
            @feedback = Gluttonberg::Blog::Article.importCSV(params[:csv].tempfile.path, {
              :additional_attributes => {
                :blog_id => @blog.id,
                :author_id => current_user.id,
                :user_id => current_user.id
              }
            })
            if @feedback == true
              flash[:notice] = "All contacts were successfully imported."
              redirect_to admin_blog_articles_path(@blog)
            end
          end
        end

        def export
          csv_data = Gluttonberg::Blog::Article.exportCSV(@articles.all)
          unless csv_data.blank?
            send_data csv_data, :type => 'text/csv; charset=utf-8' , :disposition => 'attachment' , :filename => "#{@blog.name} posts at #{Time.now.strftime('%Y-%m-%d')}.csv"
          end
        end

        protected

          def find_blog
            @blog = Gluttonberg::Blog::Weblog.where(:id => params[:blog_id]).first
            authorize! :manage_object, @blog
          end

          def find_article
            @article = Gluttonberg::Blog::Article.where(:id => params[:id]).first
            if params[:localization_id].blank?
              conditions = { :article_id => params[:id] , :locale_id => Gluttonberg::Locale.first_default.id}
              @article_localization = Gluttonberg::Blog::ArticleLocalization.where(conditions).first
            else
              @article_localization = Gluttonberg::Blog::ArticleLocalization.where(:id => params[:localization_id]).first
            end
            @article.instance_variable_set(:@current_localization, @article_localization)
            @article
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Blog::Article
          end

          def authorize_user_for_destroy
            authorize! :destroy, Gluttonberg::Blog::Article
          end

          def _log_article_changes
            localization_detail = ""
            if Gluttonberg.localized?
              localization_detail = " (#{@article_localization.locale.slug}) "
            end
            if Gluttonberg.localized?
              Gluttonberg::Feed.log(current_user,@article_localization,"#{@article_localization.title}#{localization_detail}" , "updated")
            end
          end

          def all_articles
            conditions = {:blog_id => params[:blog_id]}
            @articles = Gluttonberg::Blog::Article.where(conditions).includes(:localizations).order("created_at DESC")
          end

      end
    end
  end
end

app/controllers/gluttonberg/admin/blog/blogs_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module Blog
      class BlogsController < Gluttonberg::Admin::BaseController
        before_filter :find_blog, :only => [:show, :edit, :update, :delete, :destroy]
        before_filter :require_super_admin_user , :except => [:index]
        before_filter :authorize_user , :except => [:destroy , :delete]
        before_filter :authorize_user_for_destroy , :only => [:destroy , :delete]
        record_history :@blog

        def index
          @blogs = Gluttonberg::Blog::Weblog.all
          @blogs = @blogs.find_all{|blog| can?(:manage_object, blog) } 
          if @blogs && @blogs.size == 1
            redirect_to admin_blog_articles_path(@blogs.first)
          end
          @blogs = @blogs.paginate(:per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"), :page => params[:page])
        end

        def show
          if @blog
            redirect_to admin_blog_articles_path(@blog)
          else
            redirect_to admin_blog_path
          end
        end

        def new
          @blog = Gluttonberg::Blog::Weblog.new
        end

        def create
          @blog = Gluttonberg::Blog::Weblog.new(params[:gluttonberg_blog_weblog])
          @blog.current_user_id = current_user.id
          generic_create(@blog, {
            :name => "blog",
            :success_path => admin_blogs_path
          })
        end

        def edit
          unless params[:version].blank?
            @version = params[:version]
            @blog.revert_to(@version)
          end
        end

        def update
          @blog.assign_attributes(params[:gluttonberg_blog_weblog])
          @blog.current_user_id = current_user.id
          generic_update(@blog, {
            :name => "blog",
            :success_path => admin_blogs_path
          })
        end

        def delete
          display_delete_confirmation(
            :title      => "Delete Blog '#{@blog.name}'?",
            :url        => admin_blog_path(@blog),
            :return_url => admin_blogs_path,
            :warning    => "This will delete all the articles that belong to this blog"
          )
        end

        def destroy
          generic_destroy(@blog, {
            :name => "blog",
            :success_path => admin_blogs_path,
            :failure_path => admin_blogs_path
          })
        end


        protected

          def find_blog
            @blog = Gluttonberg::Blog::Weblog.where(:id => params[:id]).first
            authorize! :manage_object, @blog
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Blog::Weblog
          end

          def authorize_user_for_destroy
            authorize! :destroy, Gluttonberg::Blog::Weblog
          end

      end
    end
  end
end

app/controllers/gluttonberg/admin/blog/comments_controller.rb
# encoding: utf-8

module Gluttonberg
  module Admin
    module Blog
      class CommentsController < Gluttonberg::Admin::BaseController
        include ActionView::Helpers::TextHelper
        before_filter :find_blog , :except => [:all , :approved, :rejected , :pending , :spam , :moderation , :delete , :destroy , :spam_detection_for_all_pending , :block_author]
        before_filter :find_article ,  :except => [:index, :all , :approved , :rejected , :pending , :spam , :moderation , :delete , :destroy , :spam_detection_for_all_pending , :block_author]
        before_filter :authorize_user ,  :except => [:moderation]


        def index
          find_article([:comments])
          @comments = @article.comments.order("created_at DESC").paginate(:per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"), :page => params[:page] , :order => "created_at DESC")
        end

        def delete
          @comment = Gluttonberg::Blog::Comment.where(:id => params[:id]).first
          display_delete_confirmation(
            :title      => "Delete Comment ?",
            :url        => admin_comments_destroy_path(@comment),
            :return_url => :back,
            :warning    => ""
          )
        end

        def moderation
          authorize_user_for_moderation
          @comment = Gluttonberg::Blog::Comment.where(:id => params[:id]).first
          @comment.moderate(params[:moderation])
          Gluttonberg::Feed.log(current_user,@comment, truncate(@comment.body, :length => 100) , params[:moderation])
          redirect_to :back
        end

        def destroy
          @comment = Gluttonberg::Blog::Comment.where(:id => params[:id]).first
          if @comment.delete
            flash[:notice] = "The comment was successfully deleted."
            Gluttonberg::Feed.log(current_user,@comment, truncate(@comment.body, :length => 100) , "deleted")
            redirect_to admin_comments_pending_path
          else
            flash[:error] = "There was an error deleting the comment."
            redirect_to admin_comments_pending_path
          end
        end


        def pending
          @comments = ordering_and_pagination(Gluttonberg::Blog::Comment.all_pending)
          render_comments_list
        end

        def approved
          @comments = ordering_and_pagination(Gluttonberg::Blog::Comment.all_approved)
          render_comments_list
        end

        def rejected
          @comments = ordering_and_pagination(Gluttonberg::Blog::Comment.all_rejected)
          render_comments_list
        end

        def spam
          @comments = ordering_and_pagination(Gluttonberg::Blog::Comment.all_spam)
          render_comments_list
        end

        def spam_detection_for_all_pending
          Gluttonberg::Blog::Comment.spam_detection_for_all
          redirect_to admin_comments_pending_path
        end

        def block_author
          @comment = Gluttonberg::Blog::Comment.where(:id => params[:id]).first
          @comment.black_list_author
          redirect_to admin_comments_pending_path
        end



        protected

          def find_blog
            @blog = Gluttonberg::Blog::Weblog.where(:id => params[:blog_id]).first
            raise ActiveRecord::RecordNotFound unless @blog
          end

          def find_article(include_model=[])
            conditions = { :id => params[:article_id] }
            conditions[:user_id] = current_user.id unless current_user.super_admin?
            @article = Gluttonberg::Blog::Article.where(conditions).includes(include_model).first
            raise ActiveRecord::RecordNotFound unless @article
          end

          def authorize_user
            authorize! :manage, Gluttonberg::Blog::Comment
          end

          def authorize_user_for_moderation
            authorize! :moderate, Gluttonberg::Blog::Comment
          end

          def ordering_and_pagination(comments)
            comments.order("created_at DESC").paginate({
              :per_page => Gluttonberg::Setting.get_setting("number_of_per_page_items"),
              :page => params[:page]
            })
          end

          def render_comments_list
            render :template => "/gluttonberg/admin/blog/comments/index"
          end
      end
    end
  end
end

app/helpers/gluttonberg/blog/application_helper.rb
module Gluttonberg
  module Blog
    module ApplicationHelper
    end
  end
end

app/views/gluttonberg/admin/blog/articles/_form.html.haml
- unless @article_localization.blank?
  = version_alerts(@article_localization.versions , @article_localization.version, can?(:publish , Gluttonberg::Blog::Article) )
  = version_listing(@article_localization.versions , @article_localization.version)

= form_for(@article_localization, :url => url , :html => {:class => "validation auto_save"}) do  |f|
  = gb_error_messages_for(@article_localization)
  .span5
    .tabbable
      .versions.page_content_form
        - unless action_name == "new" || action_name == "create"
          - if Gluttonberg.localized? && Gluttonberg::Locale.all.length > 1
            .btn-group
              %a{ :class => "btn dropdown-toggle" , "data-toggle" => "dropdown", :href => "#"}
                Editing #{@article_localization.locale.name} Content
                %span.caret
              %ul.dropdown-menu
                - for locale in Gluttonberg::Locale.all
                  - localization = Gluttonberg::Blog::ArticleLocalization.where({ :article_id => @article.id , :locale_id => locale.id }).first
                  %li
                    %a{:href => edit_admin_blog_article_path(@blog, @article , :localization_id => localization.id) ,:id=>"edit_content_tab",:class=>"button"}
                      = "Edit #{localization.locale.name}"

      %ul.nav.nav-tabs
        %li.active
          %a{:href => "#content", "data-toggle" => "tab" }
            Content
        %li
          %a{:href => "#seo", "data-toggle" => "tab"  }
            SEO
      .tab-content
        .tab-pane.active#content
          .pad
            %p
              = f.fields_for :article , @article do |article_form|
                %p
                  = article_form.hidden_field(:user_id, :value => current_user.id) if @article.user_id.blank?
                  = article_form.hidden_field(:blog_id, :value => @blog.id) if @article.blog_id.blank?
              %p
                = f.label :title
                = f.text_field(:title, :id => "page_title" , :class => "required")

              %p
                #page_slug_holder
                  #{current_domain}#{@article.slug}
                  - unless @article.new_record?
                    = link_to("Preview", "Javascript:;", :class => "btn btn-mini preview-page", :target => "_blank", "data-url" => "#{blog_article_path(@article_localization.locale.slug ,@blog.slug, @article.slug)}?preview=true")
              .clear


              = f.fields_for :article , @article do |article_form|
                %p
                  = article_form.label :author
                  = article_form.select("author_id" ,  @authors.collect{|a| [a.email , a.id] } , :class => "required" )
              %p
                = f.label :featured_image_id
                = f.asset_browser( :featured_image_id ,  opts = { :filter => "image"   } )

              %p
                = f.label :excerpt
                = f.text_area(:excerpt  , :class => "jwysiwyg" )
              %p
                = f.label :body, "Content"
                = f.text_area(:body  , :class => "jwysiwyg" )

        .tab-pane#seo
          .pad
            = f.fields_for :article , @article do |article_form|
              .seo_body
                %p
                  = article_form.label :slug
                  = article_form.text_field(:slug, :id => 'page_slug' , :donotmodify => (action_name == "edit"  || action_name == "update"))
                %p
                  = f.label :seo_title
                  = f.text_field :seo_title , :class => "span4 "
                %p
                  = f.label :seo_keywords , "Keywords"
                  = f.text_area :seo_keywords , :class => "span4 "   , :rows => 3
                %p
                  = f.label :seo_description , "Description"
                  = f.text_area :seo_description , :class => "span4 " , :rows => 3
                %p
                  = f.label :fb_icon_id , "Facebook Icon"
                  = f.asset_browser :fb_icon_id , :class => "" , :filter => "image"


  .span4

    = f.fields_for :article , @article do |article_form|
      %legend Categories & Tags
      %p
        = article_form.label :article_category_list , "Categories"
        = article_form.text_field(:article_category_list, :class => "tags" , :rel => tags_string("article_category") )
      %p
        = article_form.label :tag_list , "Tags"
        = article_form.text_field(:tag_list, :class => "tags" , :rel => tags_string("tag") )
      %p
        %em seperate categories & tags with  a comma

      %legend Comments
      %p
        = article_form.label :disable_comments
        = article_form.check_box(:disable_comments)
      
      = submit_and_publish_controls(article_form, @article, can?(:publish , Gluttonberg::Blog::Article))

= enable_redactor("jwysiwyg")

app/views/gluttonberg/admin/blog/articles/edit.html.haml
- @page_title = "#{link_to @blog.name, admin_blog_articles_path(@blog)} > Edit #{@article.title}"

.row-fluid
  = render :partial => "/gluttonberg/admin/content/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title.html_safe

      = auto_save(@article.current_localization)
      = render :partial => "form", :locals => {:url => admin_blog_article_path(@blog, @article , :localization_id => params[:localization_id])}

app/views/gluttonberg/admin/blog/articles/import.html.haml
- @page_title = "#{link_to "Blogs", admin_blogs_path} >  #{@blog.name}".html_safe

.row-fluid
  = render :partial => "/gluttonberg/admin/content/main/sidebar"
  .span9
    .page-header
      %h1
        = @page_title.html_safe

    .row-fluid
      = form_tag(import_admin_blog_articles_path(@blog.id) , :multipart => true) do  |f|
        - if !@feedback.blank? && @feedback != true
          .error.model-error.alert.alert-block.alert-error
            %h4 Sorry, There was an error importing the CSV file.
            %p
              No records were imported, Please fix following errors and re-import the CSV file.
            %ul
              - @feedback.each_with_index do |feed , index|
                - unless feed == true
                  %li
                    Row #{index+2}
                    %ul
                      - feed.full_messages.each do |msg|
                        %li= msg
        .span5
          %legend CSV Content
          %p
            = label_tag "Select CSV File"
            = file_field_tag :csv
          %p
            The CSV file must have a header row. The column titles are supplied below. The columns can be in any order. The CSV must contain the required columns.

            %ul
              - Gluttonberg::Blog::Article.import_export_columns.each do |column|
                %li= column
          = form_controls(admin_contacts_path)

app/views/gluttonberg/admin/blog/articles/index.html.haml
- @page_title = "#{link_to "Blogs", admin_blogs_path} >  #{@blog.name}".html_safe

.row-fluid
  = render :partial => "/gluttonberg/admin/content/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title
      .subnav
        = sub_nav do
          = nav_link('Add New Post', new_admin_blog_article_path)
          = nav_link('Import', import_admin_blog_articles_path(@blog.id))
          = nav_link('Export', export_admin_blog_articles_path(@blog.id))

      - if @articles.empty?
        %p.empty No Articles
      - else
        %table{:cellpadding => 0, :cellspacing => 0, :summary => "Articles" , :class => "table table-bordered "}
          %thead
            %tr
              %th
                Article
              %th
                Comments
              %th
                Author
              %th
                Created By
              %th.controls

          %tbody
            - @articles.each do |article|
              %tr{ :class => "#{cycle("even", "odd")}"}
                %td{:style => "width:40%;"}
                  = link_to "#{article.title}", edit_admin_blog_article_path(@blog, article)
                %td{:style => "width:15%;"}
                  = link_to(pluralize(article.comments.size, "comment"), admin_blog_article_comments_path(@blog, article))
                %td{:style => "width:10%"}
                  = article.author.full_name
                %td{:style => "width:15%"}
                  = article.publishing_status
                  - unless article.published_at.blank?
                    %br
                    %span.date
                      = article.published_at.strftime("%d/%m/%Y")
                %td.controls{:style => "width:30%"}
                  .btn-group
                    %a{ :class => "btn dropdown-toggle" , "data-toggle" => "dropdown" , :href => "#"}
                      Actions
                      %span.caret
                    %ul.dropdown-menu

                      - if Gluttonberg.localized? &&  article.localizations.length > 1
                        - Gluttonberg::Locale.all.each_with_index do |locale, index|
                          - if index > 0
                            %li.divider
                          - localization = Gluttonberg::Blog::ArticleLocalization.where({ :article_id => article.id , :locale_id => locale.id }).first
                          %li.menu-section-title
                            = locale.name
                          %li
                            %a{:href => edit_admin_blog_article_path(@blog, article , :localization_id => localization.id) ,:id=>"edit_content_tab",:class=>"button"}
                              = "Edit Post"
                          %li
                            = link_to("View Post", blog_article_path(current_localization_slug ,@blog.slug, article.slug), :class => "", :target => "_blank")
                      - else
                        %li
                          = link_to "Edit Post", edit_admin_blog_article_path(@blog, article) , :class => " "
                        %li
                          = link_to("View Post", blog_article_path(:blog_id => @blog.slug, :id => article.slug), :class => "", :target => "_blank")


                      %li.divider
                      %li= link_to("Duplicate", duplicate_admin_blog_article_path( @blog, article), :class => "")

                      - if can? :destroy , Gluttonberg::Blog::Article
                        %li.divider
                        %li.danger
                          = link_to "Delete", delete_admin_blog_article_path(@blog, article) , :class => ""


        = will_paginate(@articles)

app/views/gluttonberg/admin/blog/articles/new.html.haml
- @page_title = "#{link_to @blog.name, admin_blog_articles_path(@blog)} > Add New Post"

.row-fluid
  = render :partial => "/gluttonberg/admin/content/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title.html_safe
      = render :partial => "form", :locals => {:url => admin_blog_articles_path}