config/routes.rb
Rails.application.routes.draw do
  scope :module => 'gluttonberg' do
    namespace :admin do
      scope :module => 'blog' do
        scope 'comments', :controller => :comments, :as => :comments do
          get 'spam_detection_for_all_pending' , :as => :spam_detection_for_all_pending
          get 'pending', :as => :pending
          get 'spam' , :as => :spam
          get 'approved' , :as => :approved
          get 'rejected' => :rejected , :as => :rejected
          get '/moderation/:id/:moderation' => :moderation , :as => :moderation
          get '/delete/:id' => :delete , :as => :delete
          delete '/destroy/:id' => :destroy , :as => :destroy
          get '/block_author/:id' => :block_author , :as => :block_author
        end

        resources :blogs do
          get 'delete', :on => :member
          resources :articles do
            member do
              get 'delete'
              get 'duplicate'
            end
            collection do
              match 'import'
              get 'export'
            end
            resources :comments do
              member do
                get 'delete'
              end
            end
          end
        end # blogs
      end #blog module
    end #admin
    scope :module => 'public' do
      # Blog Stuff
      scope :module => 'blog' do
        get "/articles/tag/:tag" => "articles#tag" , :as => :articles_by_tag
        get "/articles/unsubscribe/:reference" => "articles#unsubscribe" , :as => :unsubscribe_article_comments
        scope "(/:locale)" do
          resources :blogs do
            resources :articles do
              resources :comments
              get "preview"
            end
          end
        end
      end
    end#public
  end #gluttonberg
end

app/views/blog_notifier/comment_notification.html.haml
%p= "Hi #{@subscriber.author_name}"


%p= "#{@comment.writer_name} commented on \"#{@article.title}\""

%p= "#{@comment.writer_name} wrote \"#{@article.body}\""

%p= link_to "Click here to see the full thread" , @article_url

%p
  Thanks,
  %br
  = "The #{@website_title} Team"

%p
  If you don't want to receive notification emails about this article, you can 
  = link_to "unsubscribe" , @unsubscribe_url

app/views/blog_notifier/comment_notification_for_admin.html.haml
%p= "Hi #{@admin.full_name}"


%p= "#{@comment.writer_name} commented on \"#{@article.title}\""

%p= "#{@comment.writer_name} wrote \"#{@article.body}\""

%p= link_to "Click here to see the full thread" , @article_url

- if @comment.moderation_required
  %p
    = link_to "Click here to approve the comment", admin_comments_moderation_url(@comment.id, :moderation => "approve")
  %p
    = link_to "Click here to disapprove the comment", admin_comments_moderation_url(@comment.id, :moderation => "disapprove")

%p
  Thanks,
  %br
  = "The #{@website_title} Team"